# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c97696fc3e604bdcb43d6460786bb8e716449739a0007b35a88f86153e753b9ba8cf08cdd8915a9a6e08831532c7b0def571f707d0e52f117c1bdf9a37ddead

test:
  secret_key_base: 3d74863ab84f688d19be01f52e79d643fc549a5476d8d604f72da60984d2a8783bd4588f8851758b0977fe2a53335ca0a91e38ceabf26ff317daa9d0f9f3171e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
